apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextflow-user-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - pods/log
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  