apiVersion: v1
kind: List
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: nextflow-user-bind
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: nextflow-user-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:serviceaccount:nextflow-pcawg:default